### ISSUE TITLE
"Temporary" ASABFORCECONSOLE setup

### ISSUE THREAD

**Issue by eliska-n** [TeskaLabs/asab#289]
Found this in lmio-box docker-compose files (67x :speak_no_evil:):
```
    environment:
      - ASABFORCECONSOLE=1  # Temporary setup until the GitHub issue is resolved in teskalabs/asab
```
But I haven't found any active GitHub issue.
It looks magical :magic_wand:

**Comment by ateska** [comment]
Hmms.
I’ll try to seek for this - but basically this means this:

If microservice detects that it is not running on the “active” terminal, then it will not log into the stdout (on the console / screen). Other means of logging should be configured.
But this doesn’t work well with “docker logs”, so for that reason, you can enforce the stdout logging.

It is likely connected to an ability of the microservice to detect that it is running in the docker container, which is gone now. So it is not temporary any longer. The comment should be changed to “Ensure logging to standard outout so that docker logs can display logs”.

**Comment by ateska** [comment]
This is a mentioned issue:
https://github.com/TeskaLabs/asab/issues/154

**Comment by eliska-n** [comment]
Haha. It is already there: https://github.com/TeskaLabs/asab/blob/6b3936e39066caa6e3edc4f3c7e83a692448aefd/asab/log.py#L137

But I broke the `running_in_docker` method for a while. That's why I got into this trouble recently. :see_no_evil: Works now. This `running_in_docker` does not need docker.sock mounted into the container. I would keep it at least for now.

**Comment by ateska** [comment]
I agree.
