### ISSUE TITLE
Generating ID automatically in `asab.storage`

### ISSUE THREAD

**Issue by mejroslav** [TeskaLabs/asab#377]
### 1.
@Plesoun @ateska 
When executing ''examples/inmemory_storage.py", i got the following output:
``` shell
Result of get by id: None
{'_c': datetime.datetime(2023, 3, 16, 13, 2, 46, 811032, tzinfo=datetime.timezone.utc),
 '_id': None,
 '_m': datetime.datetime(2023, 3, 16, 13, 2, 46, 811151, tzinfo=datetime.timezone.utc),
 '_v': 2,
 'foo': 'buzz'}
```

I think the solution is to add below this line
https://github.com/TeskaLabs/asab/blob/b46dd3b06eceb1759f8193b3c83f10883a403804/asab/storage/upsertor.py#L27
the following code:
``` python
if self.ObjId is None:
    self.ObjId = self.__class__.generate_id()
```

### 2.
@Plesoun 
Are these lines obsolete since Elastic Search can generate IDs automatically?
https://github.com/TeskaLabs/asab/blob/b46dd3b06eceb1759f8193b3c83f10883a403804/asab/storage/elasticsearch.py#L366-L368

because of 

https://github.com/TeskaLabs/asab/blob//b46dd3b06eceb1759f8193b3c83f10883a403804//asab/storage/elasticsearch.py#L405-L411

**Comment by ateska** [comment]
1) This must work in a same way as eg. MongoDB storage.
Changes in upsertor are sensitive, be careful.
I suggest not to do it unless we have a good reason for it.

2) That exception is correct
It could be replaced by ID generator that is friendly for ElasticSearch

The generic logic in storage is:
- If the user provides ID, then this ID is used
- If the user doesn't provides ID, then the ID is auto-generated

Now auto-generation of ID can be done in two ways:
- asab.storage generates ID which is "friendly" to the technology (like in MongoDB adapter)
- storage technology itself generates ID (like in ElasticSearch)

The last point is a bit tricky. You frequently see that the ID is generated by the driver (so that it is client-side generation).
Then it could be replicated by ASAB storage - like in MongoDB.
And that's a preferred autogeneration.
